name: CI
on:
    - push
jobs:
    backend: 
      name: Build
      runs-on: ubuntu-latest
      env:
        BRANCHNAMET: default55555
      steps:
        - name: Filter Github branch
          run: | 
            echo $BRANCHNAMET
            BRANCHNAME=${GITHUB_REF#refs/heads/}
            hhh=${GITHUB_SHA}
            value="${hhh}text${BRANCHNAME}"
            echo "Filter Branch name is ${GITHUB_REF#refs/heads/}"
            echo "GITHUB_FILTER_BRANCH_NAME=$value" >> $GITHUB_ENV

        - name: Filter Github branch2
          run: |
            BRANCHNAME=${{ env.GITHUB_FILTER_BRANCH_NAME }}
            echo $BRANCHNAME
            size=${#BRANCHNAME} 
            echo "$size"


          


