name: CI
name: CI
on: [push]
jobs:
  backend:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Filter Github branch
      run: |
        # Branch name
        echo ${GITHUB_REF#refs/heads/}

    