name: CI
on:
    - push
jobs:
    backend: 
      name: Build
      runs-on: ubuntu-latest
      env:
        BRANCHNAME: default55555
      steps:
        - name: Filter Github branch
          run: |
            BRANCHNAME=${GITHUB_REF#refs/heads/}
            echo "Filter Branch name is ${GITHUB_REF#refs/heads/}"
            echo "GITHUB_FILTER_BRANCH_NAME=$BRANCHNAME" >> $GITHUB_ENV

        - name: Filter Github branch2
          run: |
            BRANCHNAME=${{ env.GITHUB_FILTER_BRANCH_NAME }}
            echo $BRANCHNAME
            size=${#BRANCHNAME} 
            echo "$size"


          


