name: CI
on:
    - push
jobs:
    backend: 
    name: Build
    runs-on: ubuntu-latest
    env:
        BRANCHNAME: DEFAULT5
    steps:
        - name: Filter Github branch
          script: |
            BRANCHNAME=${GITHUB_REF#refs/heads/}
            echo $BRANCHNAME

        - name: Filter Github branch1
          script: |
            size=${#BRANCHNAME} 
            echo "Filter Branch name is $size"
   