name: CI
on:
    - push
jobs:
    backend: 
    name: Build
    runs-on: ubuntu-latest
    env:
        Branchname: ""

    steps:
        - name: Filter Github branch
          script: |
            Branchname=${GITHUB_REF#refs/heads/}
            echo $Branchname

        - name: Filter Github branch1
          script: |
            size=${#Branchname} 
            echo $size


      

            