name: CI
on:
    - push
jobs:
    backend: 
      name: Build
      runs-on: ubuntu-latest
      steps:
        - name: Filter Github branch
          run: |
            BRANCHNAME=${GITHUB_REF#refs/heads/}
            echo $BRANCHNAME
